name: tomekf1846-Login
version: 1.0.0
main: pl.tomekf1846.Login.Spigot.MainSpigot
api-version: '1.19'
authors: [ tomekf1846 ]
description: Plugin responsible for user login
website: https://tomekf1846.pl
load: STARTUP
softdepend:
  - SkinsRestorer
  - ProtocolLib
depend:
  - tomekf1846-API
commands:
  alogin:
    description: Admin panel
    usage: /alogin
    permission: login.admin
    aliases:
      - adminlogin
      - admlogin
  login:
    description: Log in to the server
  log:
    description: Alias for /login
  l:
    description: Alias for /login
  register:
    description: Register a new user
  reg:
    description: Alias for /register
  cracked:
    description: Set cracked mode
  premium:
    description: Set premium mode
  changepass:
    description: Change password
  changepassword:
    description: Alias for /changepass
  email:
    description: Set email
  login-help:
    description: Display help menu
